### ISSUE TITLE
Problem:ReactPerf().injection.injectMeasure

### ISSUE THREAD

**Issue by hanleirx** [mjm3853/react-native-WeatherProject#1]
I met this problem when I ran your project, it is said that undefined is not an object (evaluating 'ReactPerf().injection.injectMeasure') ,I don't know why.And I don't find the file named  config.js just because you wrote this:var config = require('./config');

**Comment by mjm3853** [comment]
Thanks for opening the issue, but that behavior is intentional. 

I externalized a config.js file that has the API-key for the Weather API. I did not want to share that key in any files that I upload to GitHub, so I have added the config file to .gitignore.

There may be a better way to manage the configuration, but this repo is just code from a React-native book that I was learning from. So I have no intention of making updates at this time.

Closing the issue. thanks
